name = "vibora-docs"
compatibility_date = "2024-12-01"
workers_dev = true

routes = [
  { pattern = "www.vibora.dev/*", zone_name = "vibora.dev" },
  { pattern = "vibora.dev/*", zone_name = "vibora.dev" }
]

[assets]
directory = "./.vitepress/dist"
